@startuml
|Kunde|
start
:Går ind på hjemmesiden;
|Website|
:Have og fritid;
:Byg selv produkt;
:Carport;
:Vælg carport type;
:Carport efter egne mål;
if (Carport tag) then (Rejsning)
  :Forespørgsel;
else (Fladt tag)
  :Forespørgsel;
endif
|Fog|
:Udarbejder tilbud;
stop
@enduml