@startuml
|Website|
Start
:Sender forespørgsel;
|Fog|
:Modtager forespørgsel;
|M3 quickbyg|
:Taster oplysninger;
:Genererer tegning af carport;
:Genererer stykliste;
|Fog|
:Opdater stykliste med plukliste;
|Kunde|
:Kunde modtager tegning og tilbud;
:Betaling;
|Fog|
:Leverer stykliste;
stop
@enduml