@startuml
'https://plantuml.com/class-diagram

object Account
object Order
object Material
object Orderline
object Customer

Account <|-- Customer
Order *-- Orderline
Orderline *-- Material
Customer *-- Order

@enduml