@startuml
|Fog|
|Website|
start
:Sender forespørgsel;
|Kunde|
|Fog|
:Modtager email med forespørgsel;
:Går ind på hjemmesiden;
|Website|
:Tjekker forespørgsel;
|Fog|
:Dialog med kunde;
|Website|
:Godkender forespørgsel;
|Kunde|
:Kunde modtager tegning og tilbud;
:Betaling;
|Website|
if (Autogenerer stykliste) then
|Fog|
  :Modtager stykliste;
  stop
else
|Kunde|
  :Modtager stykliste;
stop
@enduml